// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generate.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	generate.proto

It has these top-level messages:
	UUIDRequest
	UUIDReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type UUIDRequest struct {
}

func (m *UUIDRequest) Reset()                    { *m = UUIDRequest{} }
func (m *UUIDRequest) String() string            { return proto1.CompactTextString(m) }
func (*UUIDRequest) ProtoMessage()               {}
func (*UUIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UUIDReply struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *UUIDReply) Reset()                    { *m = UUIDReply{} }
func (m *UUIDReply) String() string            { return proto1.CompactTextString(m) }
func (*UUIDReply) ProtoMessage()               {}
func (*UUIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UUIDReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto1.RegisterType((*UUIDRequest)(nil), "proto.UUIDRequest")
	proto1.RegisterType((*UUIDReply)(nil), "proto.UUIDReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Generator service

type GeneratorClient interface {
	GenerateUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDReply, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) GenerateUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDReply, error) {
	out := new(UUIDReply)
	err := grpc.Invoke(ctx, "/proto.Generator/GenerateUUID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Generator service

type GeneratorServer interface {
	GenerateUUID(context.Context, *UUIDRequest) (*UUIDReply, error)
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_GenerateUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Generator/GenerateUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateUUID(ctx, req.(*UUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUUID",
			Handler:    _Generator_GenerateUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generate.proto",
}

func init() { proto1.RegisterFile("generate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xbc,
	0x5c, 0xdc, 0xa1, 0xa1, 0x9e, 0x2e, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0xf2, 0x5c,
	0x9c, 0x10, 0x6e, 0x41, 0x4e, 0xa5, 0x90, 0x10, 0x17, 0x4b, 0x69, 0x69, 0x66, 0x8a, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x6d, 0xe4, 0xcc, 0xc5, 0xe9, 0x0e, 0x31, 0x28, 0xbf, 0x48,
	0xc8, 0x8c, 0x8b, 0x07, 0xca, 0x49, 0x05, 0xe9, 0x12, 0x12, 0x82, 0x98, 0xad, 0x87, 0x64, 0xa2,
	0x94, 0x00, 0x8a, 0x58, 0x41, 0x4e, 0xa5, 0x12, 0x43, 0x12, 0x1b, 0x58, 0xc8, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x8c, 0x5e, 0x07, 0x94, 0x00, 0x00, 0x00,
}
